spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rubies_management
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  mail:
    host: smtp.gmail.com
    port: 587
    username: hien51035@gmail.com
    password: yohmegclgdpqmtzt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org:
      hibernate:
        type: trace