spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rubies_management
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
logging:
  level:
    org:
      hibernate:
        type: trace